### PR TITLE
Add support for java.util.Currency type

### PR DESCRIPTION
**Pull request by DmitryErmolchik**
#### Issue description

https://github.com/pgjdbc/r2dbc-postgresql/issues/375
 
#### New Public APIs

None

### CODE REVIEW

**Comment by mp911de** [comment]
Not sure we want to have that. Such a codec should rather live in your own code.

**Comment by DmitryErmolchik** [comment]
Currency is a Java core class. I'm sure this codec will be used in the pair with BigDecimalCodec.
Use-case I see is storing in the DB money amount as BigDecimal and currency as Currency. 
I think this will be good to have a codec to implement this experience out of the box.

**Comment by mp911de** [comment]
You could argue the exact same way for every other Java class, Optional, ZoneId, Package, Cipher, Mac, and so on that can be obtained using a String. 

In that regard, we rather follow pgjdbc. If they support additional types that we don't, then it's fine to add an implementation. We set our to focus on core types which are pretty well supported and ans extension model that allows plugging in your own type support.

**Comment by mp911de** [comment]
Closing with out merge as per comment above.

**Pull request closed without merging**
