### PR TITLE
Lexing sql statements

### PR DESCRIPTION
**Pull request by toverdijk**
Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/.github/CONTRIBUTING.adoc).
- [x] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x] You use the code formatters provided [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/master/intellij-style.xml) and have them applied to your changes. Don't submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.

 

#### Issue description

See #312 and related issues
 
#### New Public APIs

No new public APIs

#### Additional context
Quite some changes:
* Added BasicPostgresqlSqlLexer to tokenize statements + unit tests
* Added generalized PostgresqlStatement to use instead of SimpleQueryPostgresqlStatement and ExtendedQueryPostgresqlStatement. The protocol to use is selected during execute()
* Unit Tests + integration tests for PostgresqlStatement from exiting SimpleQueryPostgresqlStatement and ExtendedQueryPostgresqlStatement tests. Added some extra integration tests to cover dollar quotes and dollar signs in quotes. 
* Removed references to SimpleQueryPostgresqlStatement and ExtendedQueryPostgresqlStatement and deleted the files and their tests

### CODE REVIEW

**Comment by mp911de** [comment]
This is pretty neat. Can you split the changes to `PostgresqlStatement` into a separate commit to make it easier to review this PR?

**Comment by davecramer** [comment]
saw it. Thx. Interesting... I'm curious how well it works

**Comment by toverdijk** [comment]
I left the interface intact in the api package, Instead I added a new PostgresqlStatement in the main package, merging the functionalities of the extended and the simple query statements. I started out with ExtendedPostgresqlStatement as a base, though. I'll try to figure out how to put this in a separate commit - I'm still a novice with Git. 

Besides, I see that I left a fix for the failing batch unit tests uncommitted at my local machine, which should fix the build issues. I'll add it.

**Comment by toverdijk** [comment]
I think I managed to figure it out - just don't know if this is the recommended way: is it?

**Comment by mp911de** [comment]
> It seems like the preferred way of doing this is just deleting the file & commit+push, followed by readding, correct? Or amending the first commit?

It mostly comes down to not having a single blob that introduces all changes but somewhat segregated changes. The ordering is after the merge not really an issue.

The changes make quite a lot use of Java 8 `Stream` API. In other projects we've found that Java 8 streams introduce a significant CPU and memory overhead. Plain old for-loops are much more efficient. Can you please replace Stream usage in your changes (e.g.:

```java
        boolean hasReturning = this.tokenizedSql.getStatements().stream()
            .flatMap(s -> s.getTokens().stream())
            .anyMatch(token -> (token.getType() == TokenType.DEFAULT)
                && (token.getValue().equalsIgnoreCase("RETURNING")));
```
)

with for-loops? Having utility methods is perfectly fine.

Java 8 streams are useful within the scope of applications but for frameworks and libraries they are too heavy for the actual value they provide.

**Comment by davecramer** [comment]
@toverdijk I hope you don't mind if I borrow this for the pgjdbc driver ?

**Comment by toverdijk** [comment]
@davecramer Of course not, feel to use it wherever you like!

**Comment by mp911de** [comment]
This is pretty exciting work. In the polishing process, I'm going to make the API package private as we do not want to expose this publicly. At least not yet.

**Comment by davecramer** [comment]
@toverdijk ya, thanks. Now I just have to modify it slightly to find ? as parameters instead of $. I'd also like to parse out the JDBC escape sequences...

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
