### PR TITLE
added parameter bind logging

### LINKED ISSUE #278: add capability to log query parameters (bindings) values
#### Describe the solution you'd like

I'd like to be able to specify logging level (say, `io.r2dbc.postgresql.PARAM`) which, when set to DEBUG or TRACE, would enable logging of parameters. 

#### Describe alternatives you've considered

`r2bc-proxy` is an alternative, but seems to be a big overhead for such a simple use-case 

#### Teachability, Documentation, Adoption, Migration Strategy

A mention in the README should suffice as a documentation

### PR DESCRIPTION
**Pull request by 62mkv**
closes #278

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/.github/CONTRIBUTING.adoc).
- [x] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x] You use the code formatters provided [here](https://github.com/pgjdbc/r2dbc-postgresql/blob/master/intellij-style.xml) and have them applied to your changes. Don't submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

Not sure what tests should I provide along with this? 

 

#### Issue description

#278 
 
#### New Public APIs

none

#### Additional context

Query Parameter values are now visible in the logs

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks for submitting a pull request. Care to attach a snippet as comment how the logs would look like?

I'm considering to slightly tweak the logging behavior. Since we have already a query logger, we might want to keep the actual SQL and the parameters somewhat close together so one can reason about the query and its parameters.

Let's see how the log output would look like before we continue here.

**Comment by 62mkv** [comment]
Hi. This is how the output looks like for me:

```
Started
2020-08-11 17:04:06.741 DEBUG 8288 --- [  restartedMain] io.r2dbc.postgresql.PARAM                : Parameter 0 value bound: %a%
2020-08-11 17:04:06.744 DEBUG 8288 --- [  restartedMain] io.r2dbc.postgresql.PARAM                : Parameter 1 value bound: 1
2020-08-11 17:04:06.744 DEBUG 8288 --- [  restartedMain] io.r2dbc.postgresql.PARAM                : Parameter 2 value bound: 2020-01-01
2020-08-11 17:04:06.773 DEBUG 8288 --- [actor-tcp-nio-1] io.r2dbc.postgresql.QUERY                : Executing query: SELECT TEMPDATA.id, TEMPDATA.textdata, TEMPDATA.tzdata FROM TEMPDATA WHERE TEMPDATA.textdata LIKE $1 AND (TEMPDATA.id > $2) AND (TEMPDATA.tzdata > $3)
Finished
```

> I'm considering to slightly tweak the logging behavior. Since we have already a query logger, we might want to keep the actual SQL and the parameters somewhat close together so one can reason about the query and its parameters.

Could you please provide a little bit more details, on how you see it accomplished? 

Thanks!

**Comment by 62mkv** [comment]
where I see a problem with the above (apart from off-by-one numbering) is what might happen in mass-parallel scenarios. So arguably, if we could put some unique query execution id into both QUERY and PARAM logger output so user could correlate those together, would be great. However at the moment I have no idea how to achieve this..

**Comment by Squiry** [comment]
I believe we need some connection id in log, in every log, not only bindings, that would help a lot.

**Comment by ttddyy** [comment]
FYI, If you want to log bindings and query all together(also connection id), r2dbc-proxy provides such capability.
[Here is sample log.](https://github.com/r2dbc/r2dbc-proxy#query-logging)
(It is multilined for display purpose but actual logging is single line, and configurable to own format)

**Comment by mp911de** [comment]
The log output looks good already. I second @Squiry's view, that we need to add context. Single-process logs are easy to understand, but in production environments we get way more log output than that.

In the SQL Server driver, we've introduced [`ConnectionContext`](https://github.com/r2dbc/r2dbc-mssql/blob/bb52fe64f2b43b605e71648a8774f48d2ff33659/src/main/java/io/r2dbc/mssql/client/ConnectionContext.java#L35) that is a factory for log messages holding the connection/channel Id for easier tracing. We could do here the same.

I'll be off for around two weeks, I can have a look afterward. Alternatively, feel free to check out the SQL server driver and introduce the contextual log message factory.

**Comment by Squiry** [comment]
We have a [processId](https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/client/ReactorNettyClient.java#L119) that can be used as a connection id provided by backend, but we have it only _after_ connection succeed.

**Comment by mp911de** [comment]
I filed #339 to capture more context so we can correlate bind calls to the actual connection.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Comment by 62mkv** [comment]
Thanks @mp911de !

**Pull request closed without merging**
